### ISSUE TITLE
[Bug]: When the higher video bit rate is used for SRT streaming, the video will frequently appear green screen or mosaic

### ISSUE THREAD

**Issue by moliyadi** [ThibaultBee/StreamPack#135]
### Version

2.6.0

### Environment that reproduces the issue

HUAWEI_Mate_30_Pro

### RTMP/SRT/... Server

SRT on SRS

### Audio configuration

default AAC

### Video configuration

H264, 
1920x1080,
bitrate: 10Mbps

### Is it reproducible in the demos application?

Yes

### Reproduction steps

1. Connect to SRT server;
2. Stream a short time;
3. Play srt with VLC;

### Expected result

The video picture is normal and clear without mosaics

### Actual result

The picture near the top of the video frame is normal, and large areas of mosaics appear in most other areas, which is more obvious in scenes with rich content or frequent changes.

### Additional context

The lower the video bitrate is set, the longer it will take to wait for this problem to appear after the streaming. If the video bit rate is set to 10 Mbps, it will be repeated almost immediately after the streaming.

https://github.com/ThibaultBee/StreamPack/issues/86
I saw the issue, I also tested it with srt-live-server, but the problem with the video still exists. 
In addition, I used Haivision Play Pro App for SRT streaming test on the same mobile phone, using the same wifi and srt server, and the video picture was clear and normal.

### Relevant logs output

There are a lot of errors when using ffplay to stream a video from StreamPack, but when using the Haivision Play Pro App to stream a video, there is no problem.

![WX20240530-105304](https://github.com/ThibaultBee/StreamPack/assets/811357/0060e8d7-2f3f-4446-82ff-751f45a0eed9)

**Comment by ThibaultBee** [comment]
Hi,

When you are using Haivision Play Pro, are you also testing in 1080p 10Mbps? Could you check the codec profile with Haivision Play Pro (In your ffplay screenshot it is `High`)?

**Comment by moliyadi** [comment]
> When you are using Haivision Play Pro, are you also testing in 1080p 10Mbps? Could you check the codec profile with Haivision Play Pro (In your ffplay screenshot it is High)?

The Haivision Play Pro can only set a maximum bitrate of 8000mbps；

PS: I found the problem, which was probably caused by PES_packet_length not being set correctly when the frame size was too large, so I committed a merge
https://github.com/ThibaultBee/StreamPack/pull/137

**Comment by tukez** [comment]
Could we get a patch release with this fix? Jitpack build does not work btw, so can't use that one: https://jitpack.io/#ThibaultBee/StreamPack
