### ISSUE TITLE
support streamid ?

### ISSUE THREAD

**Issue by DesenYang** [ThibaultBee/StreamPack#14]
thanks guy  . is this project support srt streamid in the future ?

**Comment by ThibaultBee** [comment]
Hi,
You want to set a StreamID in the srt connection? This is something I can add.
Do you need other SRT socket option? I mean, do you think it could be useful to have access to setsockopt or just to streamid?

**Comment by DesenYang** [comment]
good, if i can set srt socket options , it will be beater

**Comment by ThibaultBee** [comment]
I will only add a StreamID API because it will prevent misconfiguration of SRT connection.
Do you need other SRT socket options?
Right now, I am working on an audio issue, I will work on your feature afterwards.

**Comment by DesenYang** [comment]
hi there , reacently , i try to record screen with MediaProjection and virtualdisplay to push to srt server , i am faceing some kind of issus, could you  please and the screen record feature in the futer release

**Comment by ThibaultBee** [comment]
You can open another issue but I am not going to implement it  any day soon. I want to improve transmission before adding lot of features.

**Comment by ThibaultBee** [comment]
Is it ok with you?

**Comment by LionMiao** [comment]
> hi there , reacently , i try to record screen with MediaProjection and virtualdisplay to push to srt server , i am faceing some kind of issus, could you please and the screen record feature in the futer release

hello, can you resolve this problem?

**Comment by DesenYang** [comment]
i give up this library, and turn to javacv, with that ,you can do all of your requested feature ,in java language

**Comment by DesenYang** [comment]
check out this https://github.com/bytedeco/javacv

**Comment by ThibaultBee** [comment]
Hi,
I am sorry that StreamPack does not content both of you.
Anyway, @DesenYang did you commit your source of MediaProjection and all?
