### ISSUE TITLE
Bug: Stream timeout...

### ISSUE THREAD

**Issue by VonLisboa** [ThibaultBee/StreamPack#29]
In my test with [Simple Realtime Server](https://github.com/ossrs/srs) it is giving timeout.
I used the demo screen app, it seems that when the image is static, no data is sent to the server so it considers the connection idle and forces the disconnection.
I tested SRT and RTMP
![image](https://user-images.githubusercontent.com/31291125/165003503-335fe8b9-d5b0-485e-9e39-5c4496580977.png)

**Comment by ThibaultBee** [comment]
Hi,

> it seems that when the image is static, no data is sent to the server

I have noticed the same behaviour. This is a behaviour from the Android API that is used to capture the screen (MediaProjection/VirtualDisplay): it does not generate frame for nothing. I guess most of screen recording application should have this behaviour. I can't see easy way to fix it.

As a workaround, I can't see anythibg else than increasing the publish timeout to infinity.

Regards,
Thbault

**Comment by VonLisboa** [comment]
Yes, I also thought about this idea of putting infinite timeout, but I still haven't found any open source server with this possibility. Maybe I can customize in the source code.

Another test I did was with the RTP protocol and [libstreaming](http://guigui.uk/libstreaming/doc/) on android and it doesn't have this problem, I don't know if it's the way the protocol works, maybe an RTP extension would be interesting...

**Comment by ThibaultBee** [comment]
Hi,

> Yes, I also thought about this idea of putting infinite timeout, but I still haven't found any open source server with this possibility. Maybe I can customize in the source code.
Sorry, I can't help you on this one. Maybe there is a timeout configuration is SRS.

> Another test I did was with the RTP protocol and [libstreaming](http://guigui.uk/libstreaming/doc/) on android and it doesn't have this problem, I don't know if it's the way the protocol works, maybe an RTP extension would be interesting...

Does libstreaming provide a screen recorder embed in RTP?

Anyway, It has nothing to do with the container or network protocol. It is just a behaviour of the screen recorder (MediaProjection) on Android: it does not generate a lot of frames. You can test with the camera, you won't have this issue.

**Comment by ThibaultBee** [comment]
Hi,

I have no plan to support RTP for now.
You should try to find the publishing timeout in SRS settings. Contact them if you can't find the settings.

Best regards,
Thibault

**Comment by VonLisboa** [comment]
A possible solution to this problem is this:
**MediaFormat.KEY_REPEAT_PREVIOUS_FRAME_AFTER**
<pre>
MediaFormat.createVideoFormat(MediaFormat.MIMETYPE_VIDEO_AVC, width, height).let {
    it.setInteger(MediaFormat.KEY_REPEAT_PREVIOUS_FRAME_AFTER, 1000000 / DEFAULT_FRAME_RATE)
    it.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 1)
}
</pre>
