### ISSUE TITLE
Stream preview dimensions

### ISSUE THREAD

**Issue by itolianezzz** [ThibaultBee/StreamPack#31]
Hello! 
Thanks for the library! 
I'm using TextureView to show preview and there is transition that changes TextureView's  size (and aspect ratio)
And I need preview height and width to calculate scale for the matrix to have correct aspect ratio of preview.
Is there any possibility to get the stream preview dimensions?
Thanks

**Comment by ThibaultBee** [comment]
Hi,
There are currently no way to access to the stream resolution with StreamPack. You can keep the `VideoConfig` instance.

You must also have in mind that that the preview and the stream sizes are independant: they can have totally different resolution and aspect ratio. StreamPack manages the resolution of the stream (according to the `VideoConfig` but the preview resolution, aspect ratio,... is up to the user. You should set your TextureView size according to your UI and the size of the display, not to the stream. If you look at the `demo-camera` you will see that the SurfaceView fits the SurfaceView display. 

By the way, the former Android sample provides an `[AutoFixTextureView](https://github.com/googlearchive/android-Camera2Basic/blob/master/Application/src/main/java/com/example/android/camera2basic/AutoFitTextureView.java)` that might help you.
