### ISSUE TITLE
How can I let media player's image show positive direction when I rotate mobile?

### ISSUE THREAD

**Issue by Squall-Huang** [ThibaultBee/StreamPack#34]
Why do I change mobile from portrait to landscape .AutoFitSurfaceView showed people and things are positive direction,but media player's image not rotate people and things in positive direction?

How can I let media player's image show positive direction when I rotate mobile?

**Comment by ThibaultBee** [comment]
Hi,

If you want to get a live stream in portrait, the live stream must start in portrait, if you want to get a live stream in landscape, the live stream must start in portrait. The live stream orientation can't be changed during a live.

This is the same behaviour as the native camera application on my Pixel phone (and others devices).

The reason behind this is that most containers, decoders, players doesn't handle well a change in the orientation.

Best regards,
Thibault

**Comment by Squall-Huang** [comment]
Hi ThibaultBee:
  But when I start live stream with mobile in landscape direction, my VLC player still start in portrait and image in VLC show 90 degree direction(wrong direction).

My video config below:
```kotlin
val videoConfig =
                    VideoConfig(
                        startBitrate = 2000000,
                        fps = 30,
                        mimeType = MediaFormat.MIMETYPE_VIDEO_AVC
                    )
```

**Comment by ThibaultBee** [comment]
Hi,
What streamer do you use ? Camera or screen or custom? RTMP or SRT?

I have tested with the camera demo with RTMP and SRT Camera streamer, I can't reproduce it. 
My guess is either you have lock your phone orientation in portrait, either you have set `requireActivity().requestedOrientation`.

**Comment by Squall-Huang** [comment]
I use `CameraRtmpLiveStreamer()`
Yes, I locked my app orientation in portrait. 
My app must be locked in portrait orientation,Could I use live streaming in mobile landscape with locked in portrait and player can show in correct direction?

**Comment by ThibaultBee** [comment]
Hi,

> My app must be locked in portrait orientation,Could I use live streaming in mobile landscape with locked in portrait and player can show in correct direction?
It is not supported.
Could you lock your application in portrait and lock in landscape the only activity that contains `CameraRtmpLiveStreamer`?
I don't understand the usage. Could you explain why you want to lock in portrait while filming in landscape? Could you send me a screenshot of the activity that contains `CameraRtmpLiveStreamer`?

**Comment by Squall-Huang** [comment]
Hi:
Did you mean when rotate in portrait or in landscape each time then new a CameraRtmpLiveStreamer() at that orientation then have correction direction image?

**Comment by ThibaultBee** [comment]
No, not sure what you said will offer a nice user experience.

You can force the streaming `Activity` to landscape and let the rest of the application in portrait.

**Comment by Squall-Huang** [comment]
Hi:
I would like to let live streaming could be in portrait and landscape.

**Comment by ThibaultBee** [comment]
Lock your activity in portrait or in landcape with:
```
requireActivity().requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
```
or
```
requireActivity().requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
```

There is no other way.

**Comment by Squall-Huang** [comment]
OK. Thank you for your enthusiastic answer for all my question,ThibaultBee😄
