### ISSUE TITLE
Attempt to invoke virtual method 'int android.media.audiofx.AcousticEchoCanceler.setEnabled(boolean)' on a null object reference

### ISSUE THREAD

**Issue by Squall-Huang** [ThibaultBee/StreamPack#36]
Hi:
I often get below error crash my app. What does meaning of below Exception?

> io.github.thibaultbee.streampack.error.StreamPackError: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.audiofx.AcousticEchoCanceler.setEnabled(boolean)' on a null object reference

Error occur at this line↓
`cameraRtmpLiveStreamer?.configure(audioConfig, videoConfig)`

**Comment by ThibaultBee** [comment]
Hi,

It is not abvious at all but this issue comes from the fact that the audio permission hasn't been accepted (probably same for video).

**Comment by Squall-Huang** [comment]
Hi ThibaultBee:
After I change from these codes 
```kotlin
permissions.entries.all { entry ->
                Log.d(TAG, "entry: $entry , entry.key: ${entry.key}, entry.value: ${entry.value}")
                entry.value
}

```
to these codes.
```kotlin
permissions.getOrDefault(Manifest.permission.RECORD_AUDIO,false) &&
                    permissions.getOrDefault(Manifest.permission.CAMERA,false)-> {}
```
It seems solve this problem.

Thank you very much.😄
