### ISSUE TITLE
How to adjust Preview image to nomal?

### ISSUE THREAD

**Issue by Squall-Huang** [ThibaultBee/StreamPack#37]
Hi:
 My app's camera AutoFitSurfaceView preview's image in portrait too thin,but in landscape too fat. How to solve this problem?

**Comment by ThibaultBee** [comment]
Do you have screenshot?
I thought you used AndroidX SurfaceProvider?

**Comment by Squall-Huang** [comment]
Hi ThibaultBee:
`io.github.thibaultbee.streampack.views.AutoFitSurfaceView`
AutoFitSurfaceView stretch image.
I don't know how to solve this problem?

![Screenshot_20220616-102002](https://user-images.githubusercontent.com/36099930/174510473-392520b0-d7ac-429a-9da2-260efd98d9d3.png)

**Comment by Squall-Huang** [comment]
Hi ThibaultBee:
Thank you for reply!^^
I have chaged to another lib  made with CameraX and solve this problem.
But still very thanks for your enthusiastic reply.
