### ISSUE TITLE
No Data being received for RTMP on Android

### ISSUE THREAD

**Issue by Psionyx** [ThibaultBee/StreamPack#38]
I ran the sample app on Android. Providing an RTMP URL with the streaming key starts a successful stream, but when I check the actual data received I get nothing. This library is also being used in api.video-reactnative-live-stream

**Comment by ThibaultBee** [comment]
Hi,

What device/android version did you run your test and on which RTMP server?
Can you confirm that the server does not decode audio AND video frames?
Do you have any logs on the server side or in logcat?
It could come from either the device either the server. Just to be sure it comes from the server or the device. Could you perform the following test?

1.  Start a RTMP server with ffplay:
```
ffplay -listen 1 -i rtmp://0.0.0.0:1935/s/streamKey
```

2. Stream to RTMP endpoint  rtmp://your.computer.ip:1935/s/streamKey
3. Check that `ffplay` could decode both video and audio (on `ffplay` window)
4. Get the logs of `ffplay` and your device

**Comment by ThibaultBee** [comment]
Don't know restream or Youtube. But do you have access to a log console?
It might be really helpfull.

**Comment by ThibaultBee** [comment]
Hi,

I made fixes in the RTMP/FLV part. (branch develop).
Could you test it?

Best regards,
Thibault
