### ISSUE TITLE
Is there any release apk package?

### ISSUE THREAD

**Issue by lucentlc** [ThibaultBee/StreamPack#40]
Hi,Thanks for your masterpieces.
I was not familiar with kotlin and I try to build it, But failed。I really want to try srt on my phone, I was wondering is there any release apk package？

**Comment by ThibaultBee** [comment]
Hi,
Unfortunately, not yet. I should add an apk in the release.
If you want to build the project, you should install Android Studio, open the project and run it.

**Comment by lucentlc** [comment]
> Hi, Unfortunately, not yet. I should add an apk in the release. If you want to build the project, you should install Android Studio, open the project and run it.

OK,Thanks for your help! I will try it.Good luck!

**Comment by lucentlc** [comment]
Close this issue

**Comment by ThibaultBee** [comment]
I added an upload apks actions, so now you can find apks on the build step.
Checkout for `apks` in https://github.com/ThibaultBee/StreamPack/actions/runs/2685369159

**Comment by lucentlc** [comment]
> I added an upload apks actions, so now you can find apks on the build step. Checkout for `apks` in artifacts part of https://github.com/ThibaultBee/StreamPack/actions/runs/2685369159

Yes,I got it,Thank you very much!
