### ISSUE TITLE
Flashlight support

### ISSUE THREAD

**Issue by diegotassi** [ThibaultBee/StreamPack#41]
Would you mind enhancing it to support torch/flashlight parameter?
Thanks.

**Comment by ThibaultBee** [comment]
Hi,

If anyone is looking here. If you want to switch on/off torch, use:
```
cameraStreamer.settings.camera.flash.enable = true // or false
```
You can check that flash is available for current camera if:
```
cameraStreamer.settings.camera.flash.available == true
```

By the way, a lot of camera settings are available in `cameraStreamer.settings.camera`.

@diegotassi as you didn't find the solution easily. Do you know what I can improve so it is easy to find camera settings? (doc, readme, example, API changes,...)
