### ISSUE TITLE
How ti use srt

### ISSUE THREAD

**Issue by chenguo123456** [ThibaultBee/StreamPack#51]
Hello, when you are not connected to WIFI, srt cannot be used. Why? Looking forward to your reply, thank you!

**Comment by ThibaultBee** [comment]
Hi,

Could you explaine step by step what you are trying to achieve? And what is expected?

Best regards

**Comment by chenguo123456** [comment]
Hi!
Thank you for your reply!
First of all, I integrated the srt into my project according to your document. It uses fast integration. After the integration, I tested. During the test, I encountered a problem that the data can be transferred when the mobile phone is connected to wifi, but it is not applicable to WIFI. Only when 5G is used, I cannot connect to the server. This is the problem for the time being. Can you help me?


thank you!





Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月19日(星期三) 凌晨5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Hi,
 
Could you explaine step by step what you are trying to achieve? And what is expected?
 
Best regards

**Comment by chenguo123456** [comment]
Hi
I need your help!
thank you!




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月19日(星期三) 凌晨5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Hi,
 
Could you explaine step by step what you are trying to achieve? And what is expected?
 
Best regards

**Comment by ThibaultBee** [comment]
Hi,

Just tried in 4G and the live stream was a success.
I guess there is something wrong in your configuration. Could you share the trace from logcat and your SRT configuration?

**Comment by chenguo123456** [comment]
Thank you for your reply. I downloaded your code from git and then ran it. Do you need the address of my srt to receive services? thank you!




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上7:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Hi,
 
Just tried in 4G and the live stream was a success.
 I guess there is something wrong in your configuration. Could you share the trace from logcat and your SRT configuration?

**Comment by ThibaultBee** [comment]
Have you any SRT server ip, port, stream id,...?
What is your server IP?

**Comment by chenguo123456** [comment]
Just address is srt://live-push.bilivideo.com:1937?streamid=#!::h=live-push.bilivideo.com,r=live-bvc/?streamname=live_1361711355_70036174,key=c15a296b9b8f972ed59e6415be6c43ea,schedule=srtts,pflag=1?streamname=live_1361711355_70036174&amp;key=c15a296b9b8f972ed59e6415be6c43ea




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Have you any SRT server ip, port, stream id,...?
 What is your server IP?

**Comment by ThibaultBee** [comment]
Where did you set this address? In what fields?

**Comment by chenguo123456** [comment]
This address is set in China for live broadcast




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Where did you set this address? In what fields?

**Comment by ThibaultBee** [comment]
That is not the question. How did you set `SRT Server` IP,  Port, Stream ID and passphrase in StreamPack application? Could you take a screenshot of the SRT Server part in StreamPack demos-camera Settings?

**Comment by chenguo123456** [comment]
just like this&nbsp;




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
That is not the question. How did you set SRT Server IP,  Port, Stream ID and passphrase in StreamPack application? Could you take a screenshot of the SRT Server part in StreamPack demos-camera Settings?

**Comment by chenguo123456** [comment]
Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
That is not the question. How did you set SRT Server IP,  Port, Stream ID and passphrase in StreamPack application? Could you take a screenshot of the SRT Server part in StreamPack demos-camera Settings?

**Comment by chenguo123456** [comment]
There is no problem when the mobile phone is connected to wifi, but the server will now be rejected when using 4G. Is this a server problem or an application problem?




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
That is not the question. How did you set SRT Server IP,  Port, Stream ID and passphrase in StreamPack application? Could you take a screenshot of the SRT Server part in StreamPack demos-camera Settings?

**Comment by ThibaultBee** [comment]
> just like this&nbsp;

Just like what? Please share a screenshot!

> There is no problem when the mobile phone is connected to wifi, but the server will now be rejected when using 4G. Is this a server problem or an application problem?

I don't know. What do you mean by rejected?

**Comment by chenguo123456** [comment]
Application prompt, link rejection






---Original---
From: "Thibault ***@***.***&gt;
Date: Sat, Oct 22, 2022 23:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)




  
just like this&nbsp;
  
Just like what? Please share a screenshot!
  
There is no problem when the mobile phone is connected to wifi, but the server will now be rejected when using 4G. Is this a server problem or an application problem?
  
I don't know. What do you mean by rejected?

**Comment by chenguo123456** [comment]
Hi!
Can you understand the problems I am facing now? Can you give me some advice? You said that your 4G transmission is no problem. Would you like to ask if your SRT receiving server is built by yourself? Any ideas? Look forward to your reply, thank you!




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 晚上11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





  
just like this&nbsp;
  
Just like what? Please share a screenshot!
  
There is no problem when the mobile phone is connected to wifi, but the server will now be rejected when using 4G. Is this a server problem or an application problem?
  
I don't know. What do you mean by rejected?

**Comment by ThibaultBee** [comment]
Could you take a screenshot of the SRT Server part in StreamPack demos-camera Settings and share with us?

**Comment by chenguo123456** [comment]
Hi,
I don't have a screenshot of the SRT Server. Can you provide yours? Let's try to install it. Thank you


Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 下午2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Could you take a screenshot of the SRT Server part in StreamPack demos-camera Settings and share with us?

**Comment by chenguo123456** [comment]
I only have the IP and port of the srt. OK?




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 下午2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Could you take a screenshot of the SRT Server part in StreamPack demos-camera Settings and share with us?

**Comment by ThibaultBee** [comment]
You also must set the `streamid` otherwise the server won't know where the stream comes from.

**Comment by chenguo123456** [comment]
Thank you for your reply. Now you can use 5G to connect. I want to ask one question, is the current dependency package IP support the use of domain names? thank you


Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 凌晨1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
You also must set the streamid otherwise the server won't know where the stream comes from.

**Comment by ThibaultBee** [comment]
Yes.
Instead of the IP address, you can use "live-push.bilivideo.com"

**Comment by chenguo123456** [comment]
OK,thank you!




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Yes.
 Instead of the IP address, you can use "live-push.bilivideo.com"

**Comment by chenguo123456** [comment]
When I use this address, I report an error. This is an error message！srt://push.bj-tvart.com:9000?streamid=#!::h=push.bj-tvart.com,r=live/cg111,txSecret=85eeb11bdf671f685380a1a7bd0f1c6d,txTime=635A2A53














Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Yes.
 Instead of the IP address, you can use "live-push.bilivideo.com"

**Comment by chenguo123456** [comment]
I failed to test multiple domain names！

zhe address is&nbsp;srt://push.bj-tvart.com:9000?streamid=#!::h=push.bj-tvart.com,r=live/cg222
srt://push.bj-tvart.com:9000?streamid=#!::h=push.bj-tvart.com,r=live/cg222

Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Yes.
 Instead of the IP address, you can use "live-push.bilivideo.com"

**Comment by chenguo123456** [comment]
The Streamid is not displayed. Does it mean that the connection will fail if the Streamid is added


Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
Yes.
 Instead of the IP address, you can use "live-push.bilivideo.com"

**Comment by ThibaultBee** [comment]
In your case, you should set:
- ip = push.bj-tvart.com
- port = 9000
- streamid = #!::

If this does not work, be sure that the streamid is correct.

**Comment by chenguo123456** [comment]
I set the format as you said, but the connection failed


Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 晚上11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
In your case, you should set:
  
ip = push.bj-tvart.com
 
port = 9000
 
streamid = #!::
  
If this does not work, be sure that the streamid is correct.

**Comment by chenguo123456** [comment]
After testing, it should be the reason that the domain name is not supported, which causes the server unable to connect to the public network! Do you have any suggestions? Or where to change? thank you




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 晚上11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
In your case, you should set:
  
ip = push.bj-tvart.com
 
port = 9000
 
streamid = #!::
  
If this does not work, be sure that the streamid is correct.

**Comment by chenguo123456** [comment]
SrtEndpoint should be connected at this point，
How do I solve this problem in the process of testing?thank you


Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/StreamPack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 晚上11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/StreamPack] How ti use srt (Issue #51)





 
In your case, you should set:
  
ip = push.bj-tvart.com
 
port = 9000
 
streamid = #!::
  
If this does not work, be sure that the streamid is correct.
