### ISSUE TITLE
How to fill in Passphrase

### ISSUE THREAD

**Issue by wangpeng1** [ThibaultBee/StreamPack#53]
Hi，I used the app with srt，I want to encrypt the stream， but  i donot know how to fill the passphrase field。
Could you give me some advice？

**Comment by ThibaultBee** [comment]
Hi,

SRT passphrase is just setter/getter that hides libsrt srto_passphrase socket option.
Have a look on libsrt documentation: https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#srto_passphrase
