### ISSUE TITLE
Mirroring in landscape mode  cause the sink side to be stretched

### ISSUE THREAD

**Issue by lcksk** [ThibaultBee/StreamPack#65]
## screenrecorder 1:
If the initial state of the demo is portrait  mode, sink display is normal. 
![v_screen_source](https://user-images.githubusercontent.com/8503374/216214662-12478209-0497-44da-9a78-6e3936735809.jpg)
Then the display on the sink side is normal. then, if the mobile phone is switched between horizontal and vertical ,it just work well.
![v_sink](https://user-images.githubusercontent.com/8503374/216214939-580aa2c1-2901-4a84-b63a-0fcdbc71692f.jpg)

## screenrecorder 2:
If the initial state of the phone is horizontal, the display screen is stretched.
Before clicking the "record screen" button, keep the phone in landscape mode, and then click "record screen"
![land_source](https://user-images.githubusercontent.com/8503374/216215112-ddb2ca5e-840c-4fe2-8dab-fffca2949e44.jpg)

The screen displayed on the sink is stretched, and later, if the mobile phone switches between horizontal and vertical mode, the picture is also distorted

![land_sink](https://user-images.githubusercontent.com/8503374/216216161-89a71eaf-a9f5-495e-8cf2-efbd5feb2577.jpg)

**Comment by lcksk** [comment]
I've tried a few more phones and each has this problem -(

**Comment by ThibaultBee** [comment]
Hi,

I will have a look when I have time.

**Comment by lcksk** [comment]
> I will have a look when I have time.

Thanks for your attention. Just now, I took a moment to debug a bit and found that if the first parameter of setMVPMatrixAndViewPort() is forced to 90 degrees, the behavior is normal. Since I don't know much about gles, I can't submit a valid PR, so if you have time, you can see if there is a perfect solution. 

```
private fun initOrUpdateSurfaceTexture(surface: Surface) {
            eglSurface = ensureGlContext(EGlSurface(surface)) {
                val width = it.getWidth()
                val height = it.getHeight()
                fullFrameRect = FullFrameRect(Texture2DProgram()).apply {
                    textureId = createTextureObject()
                    setMVPMatrixAndViewPort(
                        90fps,
                        Size(width, height)
                    )
                }
```

**Comment by ThibaultBee** [comment]
Hi,
Thanks for the tips :)
Somehow, the screen recorder frame is always oriented in portrait.
I have made a fix in the `main` branch. Could you test it?

**Comment by lcksk** [comment]
Yes, using main branch to confirm the issures is gone.
