### ISSUE TITLE
Is it possible to use a dns to broadcast the streaming, say no-ip or others?

### ISSUE THREAD

**Issue by Buhos-Dev** [ThibaultBee/StreamPack#68]
### Version

2.52

### Environment that reproduces the issue

Xiaomi Redmi Note 8T

### Use case description

Is it possible to use a dns to broadcast the streaming, say no-ip or others?

**Comment by ThibaultBee** [comment]
Hi,

Are you talking of using URL like: `srt://api.provider.com/app` or `rtmp://api.provider.com/app`?
It should work. Have you tested it?

**Comment by ThibaultBee** [comment]
Stall.
Please re-open the issue if you need.
