### ISSUE TITLE
[Feat]: High latency when using the RTMP

### ISSUE THREAD

**Issue by AndroidTNTU-3** [ThibaultBee/StreamPack#83]
### Version

N/A

### Environment that reproduces the issue

Android 7, 10

### RTMP/SRT/... Server

RTMP

### Video configuration

H.264
1280x720
30fps
Bitrate - 4500 Kbps

### Is it reproducible in the demos application?

Not tested

### Reproduction steps

1. Start RTMP stream when the internet connection is not very fast.

### Expected result

Latency on the viewer side should be no more than 10 sec

### Actual result

Sometimes latency on the viewer side can be up to 1 minute during the stream when the speed of the internet connection is slow.

### Additional context

Is there a way to reduce the RTMP latency? Or add a possibility to adjust bitrate as it is implemented for the SRT streamer?

**Comment by ThibaultBee** [comment]
Hi there,

If you try to have 4500 Kbps with a slow internet connection, I guess you can't expect things to magically work. 

This project relies on librtmp/rtmpdump to handle the RTMP connection (even if I am not sure if this is a best solution). I had a look in it but I could not find anything that fit your description. If you find something, I will be okay to add this to StreamPack and its dependencies.
There is a way to set the video bitrate in every streamer with videos. See https://thibaultbee.github.io/StreamPack/core/io.github.thibaultbee.streampack.streamers.settings/-base-streamer-video-settings/index.html.
It is accessible with `streamer.settings.video.bitrate`

Also, are you sure your server does not buffer too much? Or they might be a profile to drop late frame? (I don't know the server part).

BTW, if latency is a problem for you, you should consider to use SRT instead.

**Comment by AndroidTNTU-3** [comment]
Hi.
I got it.
Thx for the explanation!
