### ISSUE TITLE
[Bug]: When using SRT to push 1080P video, the latency is severe, about 7 seconds!

### ISSUE THREAD

**Issue by TaylorsZ** [ThibaultBee/StreamPack#84]
### Version

2.5.2

### Environment that reproduces the issue

HUAWEI M5

### RTMP/SRT/... Server

SRS Server

### Audio configuration

   startBitrate = 128000,
   sampleRate = 44100,
   channelConfig = AudioFormat.CHANNEL_IN_STEREO

### Video configuration

startBitrate = 2000000, 
resolution = Size(1920, 1080),
fps = 30,
mimeType = MediaFormat.MIMETYPE_VIDEO_AVC

### Is it reproducible in the demos application?

Yes

### Reproduction steps

always

### Expected result

The video delay is less than 1s

### Actual result

When using SRT to push 1080P video, the latency is severe, about 7 seconds!

**Comment by ThibaultBee** [comment]
Hi there,

How do you measure latency?

**Comment by CzinkeM** [comment]
@TaylorsZ Hi! As I experienced and I remember correctly the server could add some additional latency depend on what software you use, also image stabilization could hurt your latency.
With correct software and networking its easy to achieve sub second latency.

**Comment by ThibaultBee** [comment]
Indeed, the server could be buffering and if you are trying to playback the stream, your player could be also buffering.

I guess in your case, the latency is for the while chain from your camera to your player which means:
```
your latency = encoder latency + srt latency + server latency + network latency + player latency.
```

Without any other context/information, as third parties are also involved in this latency, I am closing the issue.
